#!/usr/bin/env python3
"""classify — apply the VEDC standard (SPEC.md) to the deletion-durability registry.

Reads benchmarks/deletion-durability/registry.json, validates it through the same integrity
gate as build_matrix.py (so nothing unbacked can be classified), maps each engine to a VEDC
class + conformance level, and writes CLASSIFICATION.md.

A standard that is only prose is unfalsifiable. This makes it executable: the class roster is
GENERATED from committed, positive-control-validated evidence, not asserted.

Usage:
  classify.py            validate + (re)write CLASSIFICATION.md
  classify.py --check    validate only (CI gate); exit 2 on integrity failure

Exit: 0 = valid, 2 = integrity failure.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
BENCH = os.path.join(REPO_ROOT, "benchmarks", "deletion-durability")
OUT = os.path.join(HERE, "CLASSIFICATION.md")

sys.path.insert(0, BENCH)
import build_matrix as B  # reuse the integrity gate — single source of validation truth

CLASS = {  # window_class -> (VEDC id, name)
    "unbounded":    ("VEDC-U",  "Unbounded"),
    "auto-untimed": ("VEDC-AU", "Auto / untimed"),
    "auto-timed":   ("VEDC-AT", "Auto / timed"),
    "manual-only":  ("VEDC-M",  "Manual-only"),
    "none":         ("VEDC-N",  "None"),
}


def level(replication):
    """Confirmed ONLY if the SAME measurement is repeated across ≥3 seeds OR across engine
    versions (SPEC §5). Multiple delete-ratio/timing conditions measure different things and
    strengthen but do not by themselves confer Confirmed — they leave a row Provisional."""
    r = replication.lower()
    if "multi-seed" in r or "cross-version" in r:
        return "Confirmed"
    return "Provisional"


def classify(e):
    cid, name = CLASS[e["window_class"]]
    if e.get("self_identifying_deletion") and e["window_class"] != "none":
        cid += "+S"
    return cid, name, level(e["replication"])


def render(reg):
    order = {"unbounded": 0, "auto-untimed": 1, "manual-only": 2, "auto-timed": 3, "none": 4}
    engines = sorted(reg["engines"], key=lambda e: order.get(e["window_class"], 9))
    L = [
        "# VEDC Classification Roster",
        "",
        "> GENERATED by `classify.py` from `benchmarks/deletion-durability/registry.json` — do not edit.",
        f"> Standard: VEDC (see `SPEC.md`). Generated from registry **v{reg['version']}**.",
        "> Every row is validated through the same evidence gate as the registry; unbacked rows cannot appear.",
        "",
        "| Engine | VEDC class | Self-ID'd | Conformance | Evidence |",
        "|---|---|---|---|---|",
    ]
    for e in engines:
        cid, name, lvl = classify(e)
        ev = ", ".join(f"`{os.path.basename(p)}`" for p in e["evidence"]) or "—"
        sid = "yes" if (e.get("self_identifying_deletion") and e["window_class"] != "none") else "—"
        L.append(f"| **{e['engine']}** | {cid} ({name}) | {sid} | {lvl} | {ev} |")
    L += ["", "## Classes (from SPEC.md §5)", ""]
    for wc, (cid, name) in CLASS.items():
        L.append(f"- **{cid}** ({name}) — window_class `{wc}`")
    L += ["", "`+S` suffix = deletion is self-identifying (raises practical recoverability).", ""]
    # headline, computed from data
    u = [e["engine"] for e in engines if e["window_class"] == "unbounded"]
    leak = [e for e in engines if e["residue_after_delete"]]
    conf = [e for e in leak if level(e["replication"]) == "Confirmed"]
    L += [
        "## Reading",
        "",
        f"- {len(leak)} of {len(engines)} engines expose a post-delete recovery window.",
        f"- **VEDC-U (unbounded): {', '.join(u) if u else 'none'}** — the only class with no observed reclamation.",
        f"- Confirmed (multi-seed/cross-version/multi-condition) leak classifications: "
        f"{', '.join(e['engine'] for e in conf) if conf else 'none'}. "
        f"All others are Provisional (single trajectory) per SPEC §5 — replication is the next experiment.",
        "",
    ]
    return "\n".join(L) + "\n"


def main():
    check_only = "--check" in sys.argv[1:]
    reg = json.load(open(B.REGISTRY))
    errors, warnings = B.validate(reg)
    for w in warnings:
        print(f"WARN  {w}")
    if errors:
        for er in errors:
            print(f"FAIL  {er}")
        print(f"\n[FAIL] {len(errors)} integrity error(s); classification not written.")
        return 2
    rows = [classify(e) for e in reg["engines"]]
    conf = sum(1 for _, _, lvl in rows if lvl == "Confirmed")
    print(f"[OK] classified {len(rows)} engines ({conf} Confirmed, {len(rows)-conf} Provisional).")
    if not check_only:
        open(OUT, "w").write(render(reg))
        print(f"[OK] wrote {os.path.relpath(OUT, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
